version: '3.3'

services:
  db:
    image: mysql
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_DATABASE: ecommercedb
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_USER: ecommerce
      MYSQL_PASSWORD: ecommerce
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql

  keycloak:
      image: quay.io/keycloak/keycloak:latest
      container_name: keycloak
      command: start-dev
      environment:
        KC_DB: postgres
        KC_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloak
        KC_DB_USERNAME: keycloak
        KC_DB_PASSWORD: keycloak
        KC_HOSTNAME: localhost
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: admin
        TZ: Europe/Bucharest
      ports:
        - "8180:8080"
      volumes:	
        - /etc/localtime:/etc/localtime:ro
        - /etc/timezone:/etc/timezone:ro
      depends_on:
        - keycloak-db

  keycloak-db:
    image: postgres:15
    container_name: keycloak-db
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
      TZ: Europe/Bucharest	  
    ports:
      - "5432:5432"
    volumes:
      - keycloak_data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

volumes:
  keycloak_data:		  	  
