spring:
  application:
    name: ecommerce-api
  datasource:
    ecommerce:
      jdbcUrl: jdbc:mysql://localhost:3306/ecommerce
      username: ecommerce
      password: ecommerce
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        maximum-pool-size: 10
        pool-name: EcommercePool
    audit:
      jdbcUrl: jdbc:mysql://localhost:3306/ecommerce_audit
      username: ecommerce
      password: ecommerce
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        maximum-pool-size: 10
        pool-name: EcommerceAuditPool			
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update

aws:
  region: us-east-1	

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method			

logging:
  level:
    io.awspring.cloud.secretsmanager: DEBUG
    org.springframework.security.web.FilterChainProxy: DEBUG
    org.springframework.web.filter: DEBUG
    org.springframework.boot.web.servlet.FilterRegistrationBean: DEBUG

app:
  version: 0.0.5