spring:
  application:
    name: ecommerce-api
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ecommercedb
    username: ecommerce
    password: ecommerce
  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect				
    hibernate:     
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/ecommerce

aws:
  region: us-east-1
  s3:
    bucket-name: ecommerce-east1

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method			

logging:
  level:
    io.awspring.cloud.secretsmanager: DEBUG
    org.springframework.security: DEBUG

app:
  version: 0.0.7